# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directories: 
      - "/*/build.gradle" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      manual-merge:
        patterns: # Libraries which need us to take manual action to update
          - "roadrunner"
          - "pedropathing"

        exclude-patterns:
          - "MeepMeep"

        custom-labels:
          - "dependabot-manual-action-required"

      easy-merge:
        patterns:
          - "*" # Catch all others; ones that go here should always be able to be merged without human action
