name: More Info for Dependabot PRs

on:
  pull_request:
    types: [labeled]

jobs:
  apply_template:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'dependabot-manual-action-required'

    steps:
      - name: Comment extra info
        uses: actions-ecosystem/action-add-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            ## Extra Info About Merging This PR

            This PR contains an update for Roadrunner or Pedropathing, which requires additional manual file changes to stay in sync.

            ### For RoadRunner:
            Please update the files that have changed in [the quickstart](https://github.com/acmerobotics/road-runner-quickstart/tree/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode) within the `TeamCode/roadrunner` package.
            
            ### For PedroPathing
            Please update the files that have changed in [the quickstart](https://github.com/Pedro-Pathing/Quickstart/tree/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode) within the `TeamCode/pedroPathing` package.

            Best of luck! -GT
